Rails.application.routes.draw do
  get 'events/index'
  get 'events/events'
  get 'events/show'
  get 'events/edit'
  get 'follows/index'
  get 'follows/followers'
  get 'follows/following'
  get 'genres/index'
  get 'genres/edit'
  get 'groups/new'
  get 'groups/show'
  get 'groups/edit'
  get 'favorites/show'
  get 'post_comments/new'
  get 'post_comments/index'
  get 'post_comments/show'
  get 'posts/index'
  get 'posts/new'
  get 'users/show'
  get 'users/edit'
  get 'sessions/new'
  get 'registrations/new'
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
